services:
  - type: web
    name: energy-forecast-api
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker api.main:app --bind 0.0.0.0:10000 --workers 1 --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
